### ISSUE TITLE
webpack error

### ISSUE THREAD

**Issue by kanonochina** [fyndiq/fyndiq-ui#91]
I have this on my webpack client config

` module: {
        rules: [
            {
                test: /\.js?$/,
                loader: 'babel-loader',
                exclude: '/node_modules/',
                options: {
                    presets: [
                        'react', 'stage-0', ['env', {
                            target: { browsers: ['last 2 versions']}
                        }]
                    ]
                } 
            },
            {
                test: /\.scss$/,
                use: [
                    {
                        loader: 'file-loader',
                        options: {
                            name: '[name].min.css',
                            outputPath: 'assets/css/'
                        }
                    },
                    {
                        loader: 'extract-loader'
                    },
                    {
                        loader: 'css-loader',
                        options: {
                            minimize: true,
                            url: true,
                            root: webConfig.siteURL
                        }
                    },
                    {
                        loader: 'sass-loader'
                    }
                ]
            },
            {
                test: /\.css$/,
                use: ExtractTextPlugin.extract({
                  fallback: 'style-loader',
                  use: [
                    {
                      loader: 'css-loader',
                      options: {
                        importLoaders: 1,
                        sourceMap: true,
                        modules: true,
                      },
                    }, {
                      loader: 'postcss-loader',
                      options: {
                        plugins: () => ([
                          require('postcss-import'),
                          require('postcss-cssnext'),
                        ]),
                      },
                    },
                  ],
                }),
              }
        ]
    }`

and it gives me an error

`"extract-text-webpack-plugin" loader is used without the corresponding plugin`

**Comment by thibautRe** [comment]
Hey 👋 

The project is unmaintained since I left the company.

Your config is extremely hard to read with this formatting, but from what I see, you just forgot to add `ExtractTextPlugin` in the plugin section of your webpack config. See the [documentation](https://github.com/webpack-contrib/extract-text-webpack-plugin) for the (now deprecated) plugin
